const UPDATE_CURRENT_VIDEO_TITLE = 'UPDATE_CURRENT_VIDEO_TITLE';
const UPDATE_CURRENT_VIDEO_ID = 'UPDATE_CURRENT_VIDEO_ID';
const UPDATE_PLAYLIST = 'UPDATE_PLAYLIST';
const UPDATE_USERNAME = 'UPDATE_USERNAME';
const UPDATE_USERS = 'UPDATE_USERS';
const UPDATE_SUGGESTED_USER = 'UPDATE_SUGGESTED_USER';

export default {
    UPDATE_CURRENT_VIDEO_TITLE,
    UPDATE_CURRENT_VIDEO_ID,
    UPDATE_SUGGESTED_USER,
    UPDATE_PLAYLIST,
    UPDATE_USERNAME,
    UPDATE_USERS
}
