const UPDATE_CURRENT_VIDEO = 'UPDATE_CURRENT_VIDEO';
const UPDATE_PLAYLIST = 'UPDATE_PLAYLIST';
const UPDATE_USERNAME = 'UPDATE_USERNAME';
const UPDATE_USERS = 'UPDATE_USERS';
const UPDATE_VOLUME = 'UPDATE_VOLUME';
const LOADING_DATA = 'LOADING_DATA';
const DATA_LOADED_COMPLETE = 'DATA_LOADED_COMPLETE';

export default {
    UPDATE_CURRENT_VIDEO,
    UPDATE_PLAYLIST,
    UPDATE_USERNAME,
    UPDATE_USERS,
    UPDATE_VOLUME,
    LOADING_DATA,
    DATA_LOADED_COMPLETE
}
